/*
 * Copyright 2024-2026 Embabel Pty Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.embabel.chat.store.model

import com.embabel.chat.AssistantMessage
import com.embabel.chat.Message
import com.embabel.chat.MessageRole
import com.embabel.chat.SystemMessage
import com.embabel.chat.UserMessage
import org.drivine.annotation.Direction
import org.drivine.annotation.GraphRelationship
import org.drivine.annotation.GraphView
import org.drivine.annotation.NodeFragment
import org.drivine.annotation.NodeId
import org.drivine.annotation.Root
import com.embabel.chat.store.util.UUIDv7
import java.time.Instant

/**
 * Raw message node data for Neo4j persistence.
 *
 * Use this directly when you don't need the author relationship loaded,
 * or use [SimpleStoredMessage] when you need the full graph view with author.
 */
@NodeFragment(labels = ["StoredMessage"])
data class MessageData(
    /**
     * Unique message identifier (UUIDv7 recommended for chronological ordering).
     */
    @NodeId val messageId: String,

    /**
     * The role of the message sender.
     */
    val role: MessageRole,

    /**
     * The text content of the message.
     */
    val content: String,

    /**
     * When the message was created.
     */
    val createdAt: Instant,

    /**
     * Optional metadata for application-specific extensions.
     */
    val metadata: Map<String, Any>? = null,

    /**
     * TTS-friendly narration of the message content.
     * Generated by the narrator agent for assistant messages.
     */
    val narration: String? = null,

    /**
     * Dense vector embedding of [content], or `null` if no embedding has been
     * computed for this message. Stored as a list-of-float node property — a
     * shape supported uniformly across Neo4j, FalkorDB, and Memgraph, leaving
     * graph-database-specific vector index provisioning as a separate concern.
     *
     * Note: a [FloatArray] field gives [data class] equals/hashCode that
     * compare arrays by reference; this is acceptable here because no code
     * relies on structural equality between distinct [MessageData] instances
     * (the pending-buffer queue compares the same instance to itself).
     */
    val embedding: FloatArray? = null,

    /**
     * Identifier of the model that produced [embedding] (e.g. the embabel
     * [com.embabel.common.ai.model.EmbeddingService.name]). Stored so that
     * consumers can detect when stored vectors were produced by a different
     * model from the one currently configured — important if the embedding
     * model is later changed and old vectors need to be re-embedded.
     */
    val embeddingModel: String? = null,
) {
    companion object {
        /**
         * Create MessageData from any [Message] (including agent-api Message types).
         */
        @JvmStatic
        @JvmOverloads
        fun from(
            message: Message,
            messageId: String = UUIDv7.generateString()
        ): MessageData = MessageData(
            messageId = messageId,
            role = message.role,
            content = message.content,
            createdAt = message.timestamp
        )
    }

    /**
     * Convert to a rich agent-api [Message] type.
     */
    fun toMessage(): Message = when (role) {
        MessageRole.USER -> UserMessage(content = content, timestamp = createdAt)
        MessageRole.ASSISTANT -> AssistantMessage(content = content, timestamp = createdAt)
        MessageRole.SYSTEM -> SystemMessage(content = content, timestamp = createdAt)
    }
}

/**
 * A message stored in a chat session, with its author and recipient relationships.
 * Implements [Message] for compatibility with agent-api.
 *
 * This is a GraphView that includes:
 * - The message node data ([MessageData])
 * - The optional author relationship (who sent the message)
 * - The optional recipient relationship (who should receive the message)
 *
 * Example Neo4j structure:
 * ```
 * (msg:StoredMessage)-[:AUTHORED_BY]->(from:User)
 * (msg:StoredMessage)-[:SENT_TO]->(to:User)
 * ```
 *
 * If you don't need relationships loaded, you can use [MessageData] directly
 * in your own GraphView for lighter reads.
 */
@GraphView
data class SimpleStoredMessage(
    /**
     * The message node data.
     */
    @Root val message: MessageData,

    /**
     * The user who authored this message.
     * Null for system-generated messages (assistant responses) until a system user is assigned.
     */
    @GraphRelationship(type = "AUTHORED_BY", direction = Direction.OUTGOING)
    val author: StoredUser? = null,

    /**
     * The user who should receive this message.
     * Used for routing (e.g., WebSocket notifications).
     */
    @GraphRelationship(type = "SENT_TO", direction = Direction.OUTGOING)
    val recipient: StoredUser? = null,

    /**
     * Files attached to this message. Empty for the overwhelming majority of messages;
     * loading them with the message is what makes an attachment survive a conversation
     * reload rather than existing only for the turn it arrived in.
     */
    @GraphRelationship(type = "HAS_ATTACHMENT", direction = Direction.OUTGOING)
    val attachments: List<AttachmentData> = emptyList()
) : Message {
    // Convenience accessors for common properties
    val messageId: String get() = message.messageId
    override val role: MessageRole get() = message.role
    override val content: String get() = message.content
    override val timestamp: Instant get() = message.createdAt
    val metadata: Map<String, Any>? get() = message.metadata
    val narration: String? get() = message.narration
    val embedding: FloatArray? get() = message.embedding
    val embeddingModel: String? get() = message.embeddingModel

    /**
     * Convert to a rich agent-api [Message] type.
     */
    fun toMessage(): Message = message.toMessage()
}

/**
 * A message with lightweight user attribution for write operations.
 * Uses [UserRef] (ID-only) instead of full [StoredUser], so Drivine's
 * MERGE on the user node has zero fields to SET — preventing stale
 * cached properties from being written back to the DB.
 *
 * @see NewMessageInSession
 */
@GraphView
data class AttributedMessage(
    @Root val message: MessageData,

    @GraphRelationship(type = "AUTHORED_BY", direction = Direction.OUTGOING)
    val author: UserRef? = null,

    @GraphRelationship(type = "SENT_TO", direction = Direction.OUTGOING)
    val recipient: UserRef? = null,

    /** Files attached to this message. See [SimpleStoredMessage.attachments]. */
    @GraphRelationship(type = "HAS_ATTACHMENT", direction = Direction.OUTGOING)
    val attachments: List<AttachmentData> = emptyList()
)

/**
 * Write-optimized view for adding a new message to an existing session.
 *
 * Rooted on [SessionRef] with OUTGOING HAS_MESSAGE to an [AttributedMessage].
 * Since there is no prior load, Drivine has no snapshot and treats everything
 * as new — creating the message node, user relationships, and session link
 * without touching any existing node properties.
 *
 * This replaces the previous approach of loading the full [StoredSession] graph,
 * appending a message, and re-saving — which could overwrite user properties
 * (e.g., persona) with stale cached values via Drivine's dirty tracking.
 */
@GraphView
data class NewMessageInSession(
    @Root val session: SessionRef,

    @GraphRelationship(type = "HAS_MESSAGE", direction = Direction.OUTGOING)
    val message: AttributedMessage
)
